apiVersion: apps/v1
kind: Deployment
metadata:
  name: truffle-ai-deployment
  annotations:
    kubernetes.io/change-cause: <CHANGE-CAUSE>
  labels:
    app: truffle-ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truffle-ai-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: truffle-ai-deployment
    spec:
      containers:
        - name: truffle-ai-graphql-gateway
          image: <GRAPHQL-GATEWAY-IMAGE>
          ports:
            - containerPort: <GRAPHQL-GATEWAY-PORT>
          envFrom:
            - configMapRef:
                name: graphql-gateway-config
            - secretRef:
                name: graphql-gateway-secret
        - name: truffle-ai-graphql-server
          image: <GRAPHQL-SERVER-IMAGE>
          ports:
            - containerPort: <GRAPHQL-SERVER-PORT>
          envFrom:
            - configMapRef:
                name: graphql-server-config
            - secretRef:
                name: graphql-server-secret
---
apiVersion: v1
kind: Service
metadata:
  name: truffle-ai-load-balancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: truffle-ai-deployment
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: truffle-ai-repo-cronjob
spec:
  timeZone: 'Europe/Berlin'
  schedule: '0 2 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: truffle-ai-repo-cronjob
              image: <IMAGE-REPO-JOB>
              env:
                - name: TZ
                  value: $TZ
          restartPolicy: OnFailure
