serve:
  endpoint: /graphql
  playground: true
  port: 3001
sources:
  - name: Supabase
    handler:
      graphql:
        endpoint: '{env.SUPABASE_GRAPHQL_URL}'
        operationHeaders:
          apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcG5oa21rbG1idXhqd3pwaXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTkyOTcwODgsImV4cCI6MjAxNDg3MzA4OH0.KuyYduvuwEKEr2Pkb6kbupS4NFo577ch2laXucKllrk'
          Content-Type: application/json
          Authorization: '{context.headers["authorization"]}'
        schemaHeaders:
          apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcG5oa21rbG1idXhqd3pwaXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTkyOTcwODgsImV4cCI6MjAxNDg3MzA4OH0.KuyYduvuwEKEr2Pkb6kbupS4NFo577ch2laXucKllrk'
          Content-Type: application/json
          Authorization: '{context.headers["authorization"]}'
  - name: Server
    handler:
      graphql:
        endpoint: '{env.SERVER_GRAPHQL_URL}'
        source: ./../graphql_server/src/graphql/schema.ts
        operationHeaders:
          Authorization: '{context.headers["authorization"]}'
        schemaHeaders:
          Authorization: '{context.headers["authorization"]}'
additionalEnvelopPlugins: './src/envelopPlugins'
