name: 'Deploy'
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'Dockerfile'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build truffle-ai-graphql-gateway image
        working-directory: ./packages/graphql_gateway
        run: docker build -t registry.digitalocean.com/truffle-ai-containers/truffle-ai-graphql-gateway:$(echo $GITHUB_SHA | head -c7) .
      - name: Build truffle-ai-graphql-server image
        working-directory: ./packages/graphql_server
        run: docker build -t registry.digitalocean.com/truffle-ai-containers/truffle-ai-graphql-server:$(echo $GITHUB_SHA | head -c7) .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push truffle-ai-graphql-gateway image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/truffle-ai-containers/truffle-ai-graphql-gateway:$(echo $GITHUB_SHA | head -c7)
      - name: Push truffle-ai-graphql-server image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/truffle-ai-containers/truffle-ai-graphql-server:$(echo $GITHUB_SHA | head -c7)
      - name: Create deployment.yml from deployment.template.yml and add environment variables
        run: envsubst < $GITHUB_WORKSPACE/config/deployment.template.yml > $GITHUB_WORKSPACE/config/deployment.yml
      - name: Update truffle-ai-graphql-gateway in deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|<IMAGE-GRAPHQL-GATEWAY>|registry.digitalocean.com/truffle-ai-containers/truffle-ai-graphql-gateway:'${TAG}'|' $GITHUB_WORKSPACE/config/deployment.yml
      - name: Update truffle-ai-graphql-server in deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|<IMAGE-GRAPHQL-SERVER>|registry.digitalocean.com/truffle-ai-containers/truffle-ai-graphql-server:'${TAG}'|' $GITHUB_WORKSPACE/config/deployment.yml
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 truffle-ai-cluster
      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yml
      - name: Verify deployment
        run: kubectl rollout status deployment/truffle-ai-deployment
