# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
env:
  SUPABASE_REFERENCE_ID: ${{ vars.SUPABASE_REFERENCE_ID }}
  SUPABASE_URL: ${{ vars.SUPABASE_URL }}
  SUPABASE_GRAPHQL_URL: ${{ vars.SUPABASE_GRAPHQL_URL }}
  GATEWAY_PORT: ${{ vars.GATEWAY_PORT }}
  SERVER_PORT: ${{ vars.SERVER_PORT }}
  SERVER_URL: ${{ vars.SERVER_URL }}
  SERVER_GRAPHQL_URL: ${{ vars.SERVER_GRAPHQL_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - run: echo ${{ secrets.SUPABASE_API_KEY }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install npm packages
        run: NODE_ENV=test npm ci
      - name: Test
        run: NODE_ENV=test npm run test
      - name: Build
        run: NODE_ENV=production npm run build
        env:
          SUPABASE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcG5oa21rbG1idXhqd3pwaXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODQ1MTU3NTcsImV4cCI6MjAwMDA5MTc1N30.r_sih3YT0PqgHoYC59LxBA7OO2SXkAcLX44KRs1Q7O0
